version: "3.7"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "DB_APP_NAME=benzo"
      - "DB_APP_USER=benzo"
      - "DB_APP_PASS=benzo"
    volumes:
      - db_data:/var/lib/postgresql/data
      
volumes:
  db_data:
  